### ISSUE TITLE
部分内容没看懂

### ISSUE THREAD

**Issue by seetimee** [Sshuoshuo/easy-rag#1]
由于有些问题无答案，因此对于答案3加一层关键词判断，使用jieba对question进行分词，若所有的词均未在检索的文档中出现，则将答案3视为无答案，否则将答案3赋为答案2，并且为了进一步提高答案2的可靠性，在答案2的基础上给与了依据文档。

**Comment by seetimee** [comment]
请问答案三从哪里来的呀，答案一最终又起了什么作用呢

**Comment by Sshuoshuo** [comment]
由于这个比赛要提供三个答案，取最好的一个答案作为最终评分的标准，因此本方案设计了三个答案。答案三就是答案二+检索到的文档。答案一是主要答案，如果只要一个答案可以只保留答案一。

**Comment by Sshuoshuo** [comment]
> 请问答案三从哪里来的呀，答案一最终又起了什么作用呢
由于这个比赛要提供三个答案，取最好的一个答案作为最终评分的标准，因此本方案设计了三个答案。答案三就是答案二+检索到的文档。答案一是主要答案，如果只要一个答案可以只保留答案一。

**Comment by seetimee** [comment]
好的，感谢
