### ISSUE TITLE
关于输入query的处理，想问问加入system这个role作用大吗？

### ISSUE THREAD

**Issue by hhy150** [Sshuoshuo/easy-rag#2]
非常感谢你能将代码分享出来！！！
我看到代码中有一个函数make_context是加入了system这个role【system="你是一个汽车驾驶安全员,精通有关汽车驾驶、维修和保养的相关知识。"】。
想问问这段对结果有较大的正向影响吗？
因为我个人感觉本身 召回的docs就比较长，所以一般情况下我就想着直接输入LLM中，调用chat函数了。

**Comment by Sshuoshuo** [comment]
> 非常感谢你能将代码分享出来！！！ 我看到代码中有一个函数make_context是加入了system这个role【system="你是一个汽车驾驶安全员,精通有关汽车驾驶、维修和保养的相关知识。"】。 想问问这段对结果有较大的正向影响吗？ 因为我个人感觉本身 召回的docs就比较长，所以一般情况下我就想着直接输入LLM中，调用chat函数了。

感谢提问。这个我没有去做过具体的实验，我看了Qwen官方GitHub提供的脚本以及技术报告，Qwen后续是做了system强化的，所以我按照了官方的指导来完成这个小模块的，我个人的话也是比较建议加上system的，因为官方既然优化了这一块，效果在理论上是要好些的。

**Comment by hhy150** [comment]
了解了，感谢作者回复！
